
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/et_transactionservice?createDatabaseIfNotExist=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialization-mode: always

      jpa:
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          ddl-auto: update


